# GitHub Actions workflow for updating Rulebase reaction statistics
name: Update Reaction Statistics

on:
  # Run every 6 hours to keep stats fresh
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on pushes to main branch (new rules added)
  push:
    branches: ["main"]
    paths:
      - 'rules/**'

permissions:
  contents: write
  pull-requests: read
  issues: read

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm init -y
          npm install @octokit/rest
          
      - name: Update reaction statistics
        run: node update-stats.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add RULES_INDEX.md HALL_OF_FAME.md
            git commit -m "🤖 Auto-update repository statistics and reaction data [skip ci]"
            git push
          fi